version: '2'
services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    container_name: ${CONTAINER_NAME}
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - maillogs:/var/log/mail
    - ./config/:/tmp/docker-mailserver/
    env_file:
    - .env
    - env-mailserver
    cap_add:
    - NET_ADMIN
    - SYS_PTRACE
    restart: always
    
  dns:
    image: jedisct1/dnscrypt-server
    ports:
    - "443:443"
    restart: always
    
  openvpn:
    image: kylemanna/openvpn
    ports:
    - "1194:1194"
    restart: always
    
volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
  maillogs:
    driver: local
